In [1]:
import numpy as np

In [3]:
arr = np.zeros((8,4))

In [4]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
for i in range(8):
    arr[i] = i

In [11]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [19]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [21]:
arr[[1,2,3],[1,2,3]]

array([1., 2., 3.])

**Mathematical and Statistical Methods**

sum Sum of all the elements in the array or along an axis; zero-length arrays have sum 0
mean Arithmetic mean; invalid (returns NaN) on zero-length arrays
std, var Standard deviation and variance, respectively
min, max Minimum and maximum
argmin, argmax Indices of minimum and maximum elements, respectively
cumsum Cumulative sum of elements starting from 0
cumprod 

In [29]:
x = np.array([[4,5,6],[5,6,7]])

In [30]:
y = np.array([[2,3],[3,4] , [4,5]])

In [31]:
x.dot(y)

array([[47, 62],
       [56, 74]])