In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,377777777777772,7]] , np.int64)

In [3]:
myarr[0 , 1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr[0,1] 

np.int64(45)

**Conversion from other Python structures (i.e. lists and tuples)**

In [8]:
larray = np.array([[1,2,3] , [5,8,5],[4,5,6]])

In [9]:
larray.shape

(3, 3)

In [10]:
larray.size

9

In [11]:
np.array(larray)

array([[1, 2, 3],
       [5, 8, 5],
       [4, 5, 6]])

**Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
rng = np.arange(12)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
linspace = np.linspace(1,5,10)

In [18]:
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 1.11261162e-306, 8.34443015e-308]])

In [21]:
emp_like = np.empty_like(linspace) 

In [22]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
ide = np.identity(3)

In [24]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape

(99,)

In [30]:
x = [[1,2,3] , [4,5,6] , [7,1,0]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
ar.sum(axis=0)

array([12,  8,  9])

In [34]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [36]:
ar.flat

In [37]:
for i in ar.flat:
    print (i)

1
2
3
4
5
6
7
1
0


In [38]:
ar.ndim

2

In [39]:
ar.nbytes

72

In [40]:
one = np.array([1,23,4,5,5,60,6])

In [41]:
one.argmax()

np.int64(5)

In [42]:
one.argmin()

np.int64(0)

In [43]:
one.argsort()

array([0, 2, 3, 4, 6, 1, 5])

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [46]:
ar.argmin()

np.int64(8)

In [47]:
ar.argmax()

np.int64(6)

In [48]:
ar.argmax(axis=0)

array([2, 1, 1])

In [49]:
ar.argmax(axis = 1)

array([2, 2, 0])

In [50]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [51]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
ar2 = np.array([[1,2,1] , [4,0,6] , [8,1,0]])

In [53]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [54]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [55]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [56]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [57]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [60]:
np.where(ar==4)

(array([1]), array([0]))

In [61]:
import sys

In [62]:
prr = [0,4,5,23,4] 

In [63]:
nprr = np.array(prr)

In [64]:
sys.getsizeof(1) * len(prr)

140

In [65]:
nprr.itemsize * nprr.size

40

In [66]:
np.ndarray(shape=(2,2),dtype=float , order='F')

array([[6.23042070e-307, 1.69121096e-306],
       [4.67296746e-307, 7.56595733e-307]])

In [67]:
samples = np.random.standard_normal((3,3))

In [68]:
samples

array([[ 1.16226753, -0.5492317 ,  1.27128114],
       [ 0.49819278,  0.69638907, -1.68316907],
       [ 0.8682222 , -0.52061151,  0.69248344]])